// ACTIONS
export const GET_CURRENT_PATIENT = "GET_CURRENT_PATIENT";
export const GET_PATIENT_LIST = "GET_PATIENT_LIST";
export const GET_CURRENT_DOCTOR = "GET_CURRENT_DOCTOR";
export const GET_DOCTOR_LIST = "GET_DOCTOR_LIST";
export const GET_CURRENT_HOSPITAL = "GET_CURRENT_HOSPITAL";
export const GET_HOSPITAL_LIST = "GET_HOSPITAL_LIST";
export const GET_CURRENT_TRIAGE = "GET_CURRENT_TRIAGE";
export const GET_TRIAGE_LIST = "GET_TRIAGE_LIST";
export const RESET_SESSION = "RESET_SESSION";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
